# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: John Burchell
email: john.a.burchell@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm John, an avid programmer with a passion for games. This is a small portfolio to show off some
  of my own personal projects, somethings from school and other little bits on the side. Feel free to check
  out my programming blog or my painting blog!
url: "http://www.johnburchell.co.uk" # the base hostname & protocol for your site
twitter_username: JohnBurch
github_username:  JohnBurchell
linkedin_username: https://se.linkedin.com/in/johnburch
warhammer_link: http://warhammer.johnburchell.co.uk

# Build settings
markdown: kramdown